# general configuration
url: https://www.bacongravy.net
baseurl: ''
destination: public

# compass configuration
compass:
  logo: "/images/avatar.png"
  author: "David Kramer"
  description: "A page describing David Kramer"
  tagline: "A maker and a leader"
  include_content: true
  include_analytics: false
  linkedin: "https://www.linkedin.com/in/bacongravy"
  twitter: "https://twitter.com/bacongravy"
  facebook: "https://www.facebook.com/bacongravy"
  stackoverflow: "https://stackoverflow.com/users/5829298/bacongravy"
  github: "https://github.com/bacongravy"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "package.json"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
